services:
  jenkins:
    build:
      context: ./src/jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8090:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
      - jenkins_master_venv:/opt/master-venv
      - jenkins_terraform_store:/mnt/terraform
    networks:
      lab:
        aliases:
          - jenkins
      lab_access:

  infisical_backend:
    container_name: infisical-backend
    restart: unless-stopped
    depends_on:
      infisical_db:
        condition: service_healthy
      infisical_redis:
        condition: service_started
    image: infisical/infisical:latest-postgres
    pull_policy: always
    env_file: .env
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    networks:
      infisical:
        aliases:
          - backend
      lab:
        aliases:
          - infisical
      lab_access:

  infisical_redis:
    image: redis
    container_name: infisical-dev-redis
    env_file: .env
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      infisical:
        aliases:
          - redis
    volumes:
      - infisical_redis_data:/data

  infisical_db:
    container_name: infisical-db
    image: postgres:14-alpine
    restart: always
    env_file: .env
    volumes:
      - infisical_pg_data:/var/lib/postgresql/data
    networks:
      infisical:
        aliases:
          - db
          - postgres
    healthcheck:
      test: "pg_isready --username=${POSTGRES_USER} && psql --username=${POSTGRES_USER} --list"
      interval: 5s
      timeout: 10s
      retries: 10

  nginx:
    container_name: lab-nginx
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - infisical_backend
      - jenkins
    networks:
      lab_access:

volumes:
  infisical_pg_data:
    driver: local
  infisical_redis_data:
    driver: local
  jenkins_data:
    driver: local
  jenkins_master_venv:
    driver: local
  jenkins_terraform_store:
    driver: local

networks:
  infisical:
    driver: bridge
  lab:
    driver: bridge
  lab_access:
    driver: bridge
